version: '3'
services:
      
  mongodb:
    image: mongo:4.2.3-bionic
    ports:
      - ${MONGO_PORT_EXTERNAL}:${MONGO_PORT}
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_AUTH_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_AUTH_PASS}
    volumes:
      - ./mongo-entrypoint:/docker-entrypoint-initdb.d
      - mongodb:/data/db
      - mongoconfig:/data/configdb
    networks:
      - posts_net

  dbpostgres:
    image: postgres
    volumes:
      - /private/var/lib/postgresql:/var/lib/postgresql
    ports:
      - "${PG_PORT_EXTERNAL}:${PG_PORT}"
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASS}
      POSTGRES_DB: ${PG_DB_NAME}
    networks:
      - posts_net

volumes:
  mongodb:
  mongoconfig:

networks:
  posts_net: